# Filename: Dockerfile.mock
FROM golang:1.24-alpine AS builder

WORKDIR /app
# Copy hanya file mock server
COPY mock-server/main.go .

# Build binary
RUN CGO_ENABLED=0 GOOS=linux go build -o /mock-server main.go

# Final stage - Scratch (sangat ringan)
FROM scratch
COPY --from=builder /mock-server /mock-server
EXPOSE 9090
ENTRYPOINT ["/mock-server"]