version: '3.8'

services:
  # -------------------------------------------------------
  # 1. API Gateway (Target Skripsi)
  # -------------------------------------------------------
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api-gateway
    ports:
      - "8080:8080"
    environment:
      # Asumsi: App Anda bisa override config via ENV (Opsional)
      - APP_ENV=production
    volumes:
      # Mount config agar bisa diubah tanpa rebuild image
      - ./configs:/configs
    deploy:
      resources:
        limits:
          cpus: '0.5' # Batasi 0.5 core
          memory: 256M # Batasi 256MB RAM

  # -------------------------------------------------------
  # 2. Mock Server (Upstream Service)
  # -------------------------------------------------------
  mock-server:
    build:
      context: .
      dockerfile: Dockerfile.mock
    container_name: mock-server
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          cpus: '1' # Mock sangat ringan
          memory: 1G

  # -------------------------------------------------------
  # 3. K6 Load Tester
  # -------------------------------------------------------
  k6:
    image: grafana/k6:latest
    container_name: k6-load-test
    depends_on:
      - api-gateway
    environment:
      - TARGET_URL=http://api-gateway:8080
    volumes:
      - ./performance:/scripts
    command: run /scripts/load-test.js
